### ISSUE TITLE
Error when testing

### ISSUE THREAD

**Issue by patr1ckm** [civisanalytics/civis-jupyter-r#15]
Following the instructions for testing changes to notebooks, I'm getting the following error launching the notebook:

```
docker run --rm -p 8888:8888 --env-file my.env civis-jupyter-r
[I 17:21:23 CIVIS_PLATFORM_BACKEND] Retrieving notebook information from Platform
/usr/local/lib/python2.7/dist-packages/civis/_deprecation.py:69: FutureWarning: The "resources" parameter of "civis.civis.__init__" is deprecated and will be removed in v2.0.0.
  FutureWarning)
[I 17:21:28 CIVIS_PLATFORM_BACKEND] Pulling contents of notebook file from S3
[I 17:21:28 CIVIS_PLATFORM_BACKEND] Restoring notebook file from S3
[I 17:21:28 CIVIS_PLATFORM_BACKEND] Notebook file ready
[I 17:21:28 CIVIS_PLATFORM_BACKEND] Getting URLs to update notebook
[I 17:21:28 CIVIS_PLATFORM_BACKEND] Pushing latest notebook file to S3
[I 17:21:28 CIVIS_PLATFORM_BACKEND] Notebook file updated
[I 17:21:28 CIVIS_PLATFORM_BACKEND] Rendering notebook to HTML
[NbConvertApp] Converting notebook notebook.ipynb to html
[NbConvertApp] Writing 279378 bytes to notebook.html
[I 17:21:29 CIVIS_PLATFORM_BACKEND] Pushing latest notebook preview to S3
[I 17:21:29 CIVIS_PLATFORM_BACKEND] Notebook preview updated
[I 17:21:29 CIVIS_PLATFORM_BACKEND] Notebook save complete
[I 17:21:29 CIVIS_PLATFORM_BACKEND] Looking for requirements at /root/work/requirements.txt
[I 17:21:29.961 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1628, in initialize
    self.init_webapp()
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 252, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
```

My `PLATFORM_OBJECT_ID=8478`. Any tips?

**Comment by patr1ckm** [comment]
This issue doesn't seem to be related to the `IRkernel` or `civis-jupyter-notebook` package versions. I tried several combinations of both, e.g. `IRkernel 0.8.11, 0.8.14, 0.8.15` and `civis-jupyter-notebook` versions `0.4.2` and `latest`, none of which worked. The error message suggests a networking issue.

**Comment by skomanduri** [comment]
Thanks for the bug report!

`civis-jupyter-notebook` is incompatible with Jupyter Notebook 5.7.x (the current minor version) due to this bug: https://github.com/jupyter/notebook/issues/3946#issuecomment-423035232

Our 1.5.0 Docker tag is on notebook version 5.4.1 (`jupyter notebook --version`), so modifying the Dockerfile with:
```
RUN pip install notebook==5.4.1 civis-jupyter-notebook==${CIVIS_JUPYTER_NOTEBOOK_VERSION} && \
```
should fix the problem.
